<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\models\Pais;

class PaisSeeder extends Seeder
{
    public function run(): void
    {
        Pais::insert([
            ['id'=>"AF", 'nombre' => 'Afganistán'],
            ['id'=>"AL", 'nombre' => 'Albania'],
            ['id'=>"DE", 'nombre' => 'Alemania'],
            ['id'=>"AD", 'nombre' => 'Andorra'],
            ['id'=>"AO", 'nombre' => 'Angola'],
            ['id'=>"AI", 'nombre' => 'Anguilla'],
            ['id'=>"AQ", 'nombre' => 'Antártida'],
            ['id'=>"AG", 'nombre' => 'Antigua y Barbuda'],
            ['id'=>"AN", 'nombre' => 'Antillas Holandesas'],
            ['id'=>"SA", 'nombre' => 'Arabia Saudí'],
            ['id'=>"DZ", 'nombre' => 'Argelia'],
            ['id'=>"AR", 'nombre' => 'Argentina'],
            ['id'=>"AM", 'nombre' => 'Armenia'],
            ['id'=>"AW", 'nombre' => 'Aruba'],
            ['id'=>"AU", 'nombre' => 'Australia'],
            ['id'=>"AT", 'nombre' => 'Austria'],
            ['id'=>"AZ", 'nombre' => 'Azerbaiyán'],
            ['id'=>"BS", 'nombre' => 'Bahamas'],
            ['id'=>"BH", 'nombre' => 'Bahrein'],
            ['id'=>"BD", 'nombre' => 'Bangladesh'],
            ['id'=>"BB", 'nombre' => 'Barbados'],
            ['id'=>"BE", 'nombre' => 'Bélgica'],
            ['id'=>"BZ", 'nombre' => 'Belice'],
            ['id'=>"BJ", 'nombre' => 'Benin'],
            ['id'=>"BM", 'nombre' => 'Bermudas'],
            ['id'=>"BY", 'nombre' => 'Bielorrusia'],
            ['id'=>"MM", 'nombre' => 'Birmania'],
            ['id'=>"BO", 'nombre' => 'Bolivia'],
            ['id'=>"BA", 'nombre' => 'Bosnia y Herzegovina'],
            ['id'=>"BW", 'nombre' => 'Botswana'],
            ['id'=>"BR", 'nombre' => 'Brasil'],
            ['id'=>"BN", 'nombre' => 'Brunei'],
            ['id'=>"BG", 'nombre' => 'Bulgaria'],
            ['id'=>"BF", 'nombre' => 'Burkina Faso'],
            ['id'=>"BI", 'nombre' => 'Burundi'],
            ['id'=>"BT", 'nombre' => 'Bután'],
            ['id'=>"CV", 'nombre' => 'Cabo Verde'],
            ['id'=>"KH", 'nombre' => 'Camboya'],
            ['id'=>"CM", 'nombre' => 'Camerún'],
            ['id'=>"CA", 'nombre' => 'Canadá'],
            ['id'=>"TD", 'nombre' => 'Chad'],
            ['id'=>"CL", 'nombre' => 'Chile'],
            ['id'=>"CN", 'nombre' => 'China'],
            ['id'=>"CY", 'nombre' => 'Chipre'],
            ['id'=>"VA", 'nombre' => 'Ciudad del Vaticano (Santa Sede)'],
            ['id'=>"CO", 'nombre' => 'Colombia'],
            ['id'=>"KM", 'nombre' => 'Comores'],
            ['id'=>"CG", 'nombre' => 'Congo'],
            ['id'=>"CD", 'nombre' => 'Congo, República Democrática del'],
            ['id'=>"KR", 'nombre' => 'Corea'],
            ['id'=>"KP", 'nombre' => 'Corea del Norte'],
            ['id'=>"CI", 'nombre' => 'Costa de Marfíl'],
            ['id'=>"CR", 'nombre' => 'Costa Rica'],
            ['id'=>"HR", 'nombre' => 'Croacia (Hrvatska)'],
            ['id'=>"CU", 'nombre' => 'Cuba'],
            ['id'=>"DK", 'nombre' => 'Dinamarca'],
            ['id'=>"DJ", 'nombre' => 'Djibouti'],
            ['id'=>"DM", 'nombre' => 'Dominica'],
            ['id'=>"EC", 'nombre' => 'Ecuador'],
            ['id'=>"EG", 'nombre' => 'Egipto'],
            ['id'=>"SV", 'nombre' => 'El Salvador'],
            ['id'=>"AE", 'nombre' => 'Emiratos Árabes Unidos'],
            ['id'=>"ER", 'nombre' => 'Eritrea'],
            ['id'=>"SI", 'nombre' => 'Eslovenia'],
            ['id'=>"ES", 'nombre' => 'selected>España'],
            ['id'=>"US", 'nombre' => 'Estados Unidos'],
            ['id'=>"EE", 'nombre' => 'Estonia'],
            ['id'=>"ET", 'nombre' => 'Etiopía'],
            ['id'=>"FJ", 'nombre' => 'Fiji'],
            ['id'=>"PH", 'nombre' => 'Filipinas'],
            ['id'=>"FI", 'nombre' => 'Finlandia'],
            ['id'=>"FR", 'nombre' => 'Francia'],
            ['id'=>"GA", 'nombre' => 'Gabón'],
            ['id'=>"GM", 'nombre' => 'Gambia'],
            ['id'=>"GE", 'nombre' => 'Georgia'],
            ['id'=>"GH", 'nombre' => 'Ghana'],
            ['id'=>"GI", 'nombre' => 'Gibraltar'],
            ['id'=>"GD", 'nombre' => 'Granada'],
            ['id'=>"GR", 'nombre' => 'Grecia'],
            ['id'=>"GL", 'nombre' => 'Groenlandia'],
            ['id'=>"GP", 'nombre' => 'Guadalupe'],
            ['id'=>"GU", 'nombre' => 'Guam'],
            ['id'=>"GT", 'nombre' => 'Guatemala'],
            ['id'=>"GY", 'nombre' => 'Guayana'],
            ['id'=>"GF", 'nombre' => 'Guayana Francesa'],
            ['id'=>"GN", 'nombre' => 'Guinea'],
            ['id'=>"GQ", 'nombre' => 'Guinea Ecuatorial'],
            ['id'=>"GW", 'nombre' => 'Guinea-Bissau'],
            ['id'=>"HT", 'nombre' => 'Haití'],
            ['id'=>"HN", 'nombre' => 'Honduras'],
            ['id'=>"HU", 'nombre' => 'Hungría'],
            ['id'=>"IN", 'nombre' => 'India'],
            ['id'=>"ID", 'nombre' => 'Indonesia'],
            ['id'=>"IQ", 'nombre' => 'Irak'],
            ['id'=>"IR", 'nombre' => 'Irán'],
            ['id'=>"IE", 'nombre' => 'Irlanda'],
            ['id'=>"BV", 'nombre' => 'Isla Bouvet'],
            ['id'=>"CX", 'nombre' => 'Isla de Christmas'],
            ['id'=>"IS", 'nombre' => 'Islandia'],
            ['id'=>"KY", 'nombre' => 'Islas Caimán'],
            ['id'=>"CK", 'nombre' => 'Islas Cook'],
            ['id'=>"CC", 'nombre' => 'Islas de Cocos o Keeling'],
            ['id'=>"FO", 'nombre' => 'Islas Faroe'],
            ['id'=>"HM", 'nombre' => 'Islas Heard y McDonald'],
            ['id'=>"FK", 'nombre' => 'Islas Malvinas'],
            ['id'=>"MP", 'nombre' => 'Islas Marianas del Norte'],
            ['id'=>"MH", 'nombre' => 'Islas Marshall'],
            ['id'=>"UM", 'nombre' => 'Islas menores de Estados Unidos'],
            ['id'=>"PW", 'nombre' => 'Islas Palau'],
            ['id'=>"SB", 'nombre' => 'Islas Salomón'],
            ['id'=>"SJ", 'nombre' => 'Islas Svalbard y Jan Mayen'],
            ['id'=>"TK", 'nombre' => 'Islas Tokelau'],
            ['id'=>"TC", 'nombre' => 'Islas Turks y Caicos'],
            ['id'=>"VI", 'nombre' => 'Islas Vírgenes (EEUU)'],
            ['id'=>"VG", 'nombre' => 'Islas Vírgenes (Reino Unido)'],
            ['id'=>"WF", 'nombre' => 'Islas Wallis y Futuna'],
            ['id'=>"IL", 'nombre' => 'Israel'],
            ['id'=>"IT", 'nombre' => 'Italia'],
            ['id'=>"JM", 'nombre' => 'Jamaica'],
            ['id'=>"JP", 'nombre' => 'Japón'],
            ['id'=>"JO", 'nombre' => 'Jordania'],
            ['id'=>"KZ", 'nombre' => 'Kazajistán'],
            ['id'=>"KE", 'nombre' => 'Kenia'],
            ['id'=>"KG", 'nombre' => 'Kirguizistán'],
            ['id'=>"KI", 'nombre' => 'Kiribati'],
            ['id'=>"KW", 'nombre' => 'Kuwait'],
            ['id'=>"LA", 'nombre' => 'Laos'],
            ['id'=>"LS", 'nombre' => 'Lesotho'],
            ['id'=>"LV", 'nombre' => 'Letonia'],
            ['id'=>"LB", 'nombre' => 'Líbano'],
            ['id'=>"LR", 'nombre' => 'Liberia'],
            ['id'=>"LY", 'nombre' => 'Libia'],
            ['id'=>"LI", 'nombre' => 'Liechtenstein'],
            ['id'=>"LT", 'nombre' => 'Lituania'],
            ['id'=>"LU", 'nombre' => 'Luxemburgo'],
            ['id'=>"MK", 'nombre' => 'Macedonia, Ex-República Yugoslava de'],
            ['id'=>"MG", 'nombre' => 'Madagascar'],
            ['id'=>"MY", 'nombre' => 'Malasia'],
            ['id'=>"MW", 'nombre' => 'Malawi'],
            ['id'=>"MV", 'nombre' => 'Maldivas'],
            ['id'=>"ML", 'nombre' => 'Malí'],
            ['id'=>"MT", 'nombre' => 'Malta'],
            ['id'=>"MA", 'nombre' => 'Marruecos'],
            ['id'=>"MQ", 'nombre' => 'Martinica'],
            ['id'=>"MU", 'nombre' => 'Mauricio'],
            ['id'=>"MR", 'nombre' => 'Mauritania'],
            ['id'=>"YT", 'nombre' => 'Mayotte'],
            ['id'=>"MX", 'nombre' => 'México'],
            ['id'=>"FM", 'nombre' => 'Micronesia'],
            ['id'=>"MD", 'nombre' => 'Moldavia'],
            ['id'=>"MC", 'nombre' => 'Mónaco'],
            ['id'=>"MN", 'nombre' => 'Mongolia'],
            ['id'=>"MS", 'nombre' => 'Montserrat'],
            ['id'=>"MZ", 'nombre' => 'Mozambique'],
            ['id'=>"NA", 'nombre' => 'Namibia'],
            ['id'=>"NR", 'nombre' => 'Nauru'],
            ['id'=>"NP", 'nombre' => 'Nepal'],
            ['id'=>"NI", 'nombre' => 'Nicaragua'],
            ['id'=>"NE", 'nombre' => 'Níger'],
            ['id'=>"NG", 'nombre' => 'Nigeria'],
            ['id'=>"NU", 'nombre' => 'Niue'],
            ['id'=>"NF", 'nombre' => 'Norfolk'],
            ['id'=>"NO", 'nombre' => 'Noruega'],
            ['id'=>"NC", 'nombre' => 'Nueva Caledonia'],
            ['id'=>"NZ", 'nombre' => 'Nueva Zelanda'],
            ['id'=>"OM", 'nombre' => 'Omán'],
            ['id'=>"NL", 'nombre' => 'Países Bajos'],
            ['id'=>"PA", 'nombre' => 'Panamá'],
            ['id'=>"PG", 'nombre' => 'Papúa Nueva Guinea'],
            ['id'=>"PK", 'nombre' => 'Paquistán'],
            ['id'=>"PY", 'nombre' => 'Paraguay'],
            ['id'=>"PE", 'nombre' => 'Perú'],
            ['id'=>"PN", 'nombre' => 'Pitcairn'],
            ['id'=>"PF", 'nombre' => 'Polinesia Francesa'],
            ['id'=>"PL", 'nombre' => 'Polonia'],
            ['id'=>"PT", 'nombre' => 'Portugal'],
            ['id'=>"PR", 'nombre' => 'Puerto Rico'],
            ['id'=>"QA", 'nombre' => 'Qatar'],
            ['id'=>"UK", 'nombre' => 'Reino Unido'],
            ['id'=>"CF", 'nombre' => 'República Centroafricana'],
            ['id'=>"CZ", 'nombre' => 'República Checa'],
            ['id'=>"ZA", 'nombre' => 'República de Sudáfrica'],
            ['id'=>"DO", 'nombre' => 'República Dominicana'],
            ['id'=>"SK", 'nombre' => 'República Eslovaca'],
            ['id'=>"RE", 'nombre' => 'Reunión'],
            ['id'=>"RW", 'nombre' => 'Ruanda'],
            ['id'=>"RO", 'nombre' => 'Rumania'],
            ['id'=>"RU", 'nombre' => 'Rusia'],
            ['id'=>"EH", 'nombre' => 'Sahara Occidental'],
            ['id'=>"KN", 'nombre' => 'Saint Kitts y Nevis'],
            ['id'=>"WS", 'nombre' => 'Samoa'],
            ['id'=>"AS", 'nombre' => 'Samoa Americana'],
            ['id'=>"SM", 'nombre' => 'San Marino'],
            ['id'=>"VC", 'nombre' => 'San Vicente y Granadinas'],
            ['id'=>"SH", 'nombre' => 'Santa Helena'],
            ['id'=>"LC", 'nombre' => 'Santa Lucía'],
            ['id'=>"ST", 'nombre' => 'Santo Tomé y Príncipe'],
            ['id'=>"SN", 'nombre' => 'Senegal'],
            ['id'=>"SC", 'nombre' => 'Seychelles'],
            ['id'=>"SL", 'nombre' => 'Sierra Leona'],
            ['id'=>"SG", 'nombre' => 'Singapur'],
            ['id'=>"SY", 'nombre' => 'Siria'],
            ['id'=>"SO", 'nombre' => 'Somalia'],
            ['id'=>"LK", 'nombre' => 'Sri Lanka'],
            ['id'=>"PM", 'nombre' => 'St Pierre y Miquelon'],
            ['id'=>"SZ", 'nombre' => 'Suazilandia'],
            ['id'=>"SD", 'nombre' => 'Sudán'],
            ['id'=>"SE", 'nombre' => 'Suecia'],
            ['id'=>"CH", 'nombre' => 'Suiza'],
            ['id'=>"SR", 'nombre' => 'Surinam'],
            ['id'=>"TH", 'nombre' => 'Tailandia'],
            ['id'=>"TW", 'nombre' => 'Taiwán'],
            ['id'=>"TZ", 'nombre' => 'Tanzania'],
            ['id'=>"TJ", 'nombre' => 'Tayikistán'],
            ['id'=>"TF", 'nombre' => 'Territorios franceses del Sur'],
            ['id'=>"TP", 'nombre' => 'Timor Oriental'],
            ['id'=>"TG", 'nombre' => 'Togo'],
            ['id'=>"TO", 'nombre' => 'Tonga'],
            ['id'=>"TT", 'nombre' => 'Trinidad y Tobago'],
            ['id'=>"TN", 'nombre' => 'Túnez'],
            ['id'=>"TM", 'nombre' => 'Turkmenistán'],
            ['id'=>"TR", 'nombre' => 'Turquía'],
            ['id'=>"TV", 'nombre' => 'Tuvalu'],
            ['id'=>"UA", 'nombre' => 'Ucrania'],
            ['id'=>"UG", 'nombre' => 'Uganda'],
            ['id'=>"UY", 'nombre' => 'Uruguay'],
            ['id'=>"UZ", 'nombre' => 'Uzbekistán'],
            ['id'=>"VU", 'nombre' => 'Vanuatu'],
            ['id'=>"VE", 'nombre' => 'Venezuela'],
            ['id'=>"VN", 'nombre' => 'Vietnam'],
            ['id'=>"YE", 'nombre' => 'Yemen'],
            ['id'=>"YU", 'nombre' => 'Yugoslavia'],
            ['id'=>"ZM", 'nombre' => 'Zambia'],
            ['id'=>"ZW", 'nombre' => 'Zimbabue']
        ]);
    }
}
