<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\models\Responsabilidad;

class ResponsabilidadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Responsabilidad::insert([
            ['nombre' => 'DIRECTOR (a) NACIONAL DEL FFM', 'nivel' => '1'],
            ['nombre' => 'DIRECTOR (a) NACIONAL EJECUTIVA DEL FFM', 'nivel' => '1'],
            ['nombre' => 'DIRECTOR (a) NACIONAL DE ORGANIZACION', 'nivel' => '1'],
            ['nombre' => 'SUD-DIRECTOR (a) NACIONAL DE ORGANIZACION', 'nivel' => '1'],
            ['nombre' => 'FUNCIONAMIENTO NACIONAL DE ORGANIZACION', 'nivel' => '1'],
            ['nombre' => 'RESPONSABLE NACIONAL DE SUB ÁREA-ORGANIZACION', 'nivel' => '1'],
            ['nombre' => 'EQUIPO NACIONAL DE ORGANIZACION', 'nivel' => '1'],
            ['nombre' => 'DIRECTOR (a) NACIONAL DE PUESTO DE COMANDO', 'nivel' => '1'],
            ['nombre' => 'SUD-DIRECTOR (a) NACIONAL DE PUESTO DE COMANDO', 'nivel' => '1'],
            ['nombre' => 'FUNCIONAMIENTO NACIONAL DE PUESTO DE COMANDO', 'nivel' => '1'],
            ['nombre' => 'RESPONSABLE NACIONAL DE SUB ÁREA-PUESTO DE COMANDO', 'nivel' => '1'],
            ['nombre' => 'EQUIPO NACIONAL DE PUESTO DE COMANDO', 'nivel' => '1'],
            ['nombre' => 'DIRECTOR (a) NACIONAL DE FORMACION', 'nivel' => '1'],
            ['nombre' => 'SUD-DIRECTOR (a) NACIONAL DE FORMACION', 'nivel' => '1'],
            ['nombre' => 'FUNCIONAMIENTO NACIONAL DE FORMACION', 'nivel' => '1'],
            ['nombre' => 'RESPONSABLE NACIONAL DE SUB ÁREA-FORMACION', 'nivel' => '1'],
            ['nombre' => 'EQUIPO NACIONAL DE FORMACION', 'nivel' => '1'],
            ['nombre' => 'DIRECTOR (a) NACIONAL DE MOVILIZACION Y PROPAGANDA', 'nivel' => '1'],
            ['nombre' => 'SUD-DIRECTOR (a) NACIONAL DE MOVILIZACION Y PROPAGANDA', 'nivel' => '1'],
            ['nombre' => 'FUNCIONAMIENTO NACIONAL DE MOVILIZACION Y PROPAGANDA', 'nivel' => '1'],
            ['nombre' => 'RESPONSABLE NACIONAL DE SUB ÁREA-MOVILIZACION Y PROPAGANDA', 'nivel' => '1'],
            ['nombre' => 'EQUIPO NACIONAL DE PROPAGANDA', 'nivel' => '1'],
            ['nombre' => 'DIRECTOR (a) NACIONAL DE ESTRATEGIA COMUNICACIONAL', 'nivel' => '1'],
            ['nombre' => 'SUD-DIRECTOR (a) NACIONAL DE ESTRATEGIA COMUNICACIONAL', 'nivel' => '1'],
            ['nombre' => 'FUNCIONAMIENTO NACIONAL DE ESTRATEGIA COMUNICACIONAL', 'nivel' => '1'],
            ['nombre' => 'RESPONSABLE NACIONAL DE SUB ÁREA- ESTRATEGIA COMUNICACIONAL', 'nivel' => '1'],
            ['nombre' => 'EQUIPO NACIONAL DE ESTRATEGIA COMUNICACIONAL', 'nivel' => '1'],
            ['nombre' => 'DIRECTOR (a) NACIONAL DE ECONOMIA', 'nivel' => '1'],
            ['nombre' => 'SUD-DIRECTOR (a) NACIONAL DE ECONOMIA', 'nivel' => '1'],
            ['nombre' => 'FUNCIONAMIENTO NACIONAL DE ECONOMIA', 'nivel' => '1'],
            ['nombre' => 'RESPONSABLE NACIONAL DE SUB ÁREA- ECONOMIA', 'nivel' => '1'],
            ['nombre' => 'EQUIPO NACIONAL DE ECONOMIA', 'nivel' => '1'],
            ['nombre' => 'DIRECTOR (a) NACIONAL DE DEFENSA INTEGRAL DE LA PATRIA', 'nivel' => '1'],
            ['nombre' => 'SUD-DIRECTOR (a) NACIONAL DE DEFENSA INTEGRAL DE LA PATRIA', 'nivel' => '1'],
            ['nombre' => 'FUNCIONAMIENTO NACIONAL DE DEFENSA INTEGRAL DE LA PATRIA', 'nivel' => '1'],
            ['nombre' => 'RESPONSABLE NACIONAL DE SUB ÁREA- DEFENSA INTEGRAL DE LA PATRIA', 'nivel' => '1'],
            ['nombre' => 'EQUIPO NACIONAL DE DEFENSA INTEGRAL DE LA PATRIA', 'nivel' => '1'],
            ['nombre' => 'DIRECTOR (a) NACIONAL DE ECONOMIA PRODUCTIVA', 'nivel' => '1'],
            ['nombre' => 'SUD-DIRECTOR (a) NACIONAL DE ECONOMIA PRODUCTIVA', 'nivel' => '1'],
            ['nombre' => 'FUNCIONAMIENTO NACIONAL DE ECONOMIA PRODUCTIVA', 'nivel' => '1'],
            ['nombre' => 'RESPONSABLE NACIONAL DE SUB ÁREA- ECONOMIA PRODUCTIVA', 'nivel' => '1'],
            ['nombre' => 'EQUIPO NACIONAL DE ECONOMIA PRODUCTIVA', 'nivel' => '1'],
            ['nombre' => 'DIRECTOR (a) NACIONAL DE SOMOS VENEZUELA', 'nivel' => '1'],
            ['nombre' => 'SUD-DIRECTOR (a) NACIONAL DE SOMOS VENEZUELA', 'nivel' => '1'],
            ['nombre' => 'FUNCIONAMIENTO NACIONAL DE SOMOS VENEZUELA', 'nivel' => '1'],
            ['nombre' => 'RESPONSABLE NACIONAL DE SUB ÁREA- SOMOS VENEZUELA', 'nivel' => '1'],
            ['nombre' => 'EQUIPO NACIONAL DE SOMOS VENEZUELA', 'nivel' => '1'],
            ['nombre' => 'DIRECTOR (a) NACIONAL DE LA GMVV', 'nivel' => '1'],
            ['nombre' => 'SUD-DIRECTOR (a) NACIONAL DE LA GMVV', 'nivel' => '1'],
            ['nombre' => 'FUNCIONAMIENTO NACIONAL DE LA GMVV', 'nivel' => '1'],
            ['nombre' => 'RESPONSABLE NACIONAL DE SUB ÁREA- LA GMVV', 'nivel' => '1'],
            ['nombre' => 'EQUIPO NACIONAL DE LA GMVV', 'nivel' => '1'],
            ['nombre' => 'EMN EN INSTITUCION', 'nivel' => '1'],
            ['nombre' => 'EQUIPONACIONAL EN INSTITUCION', 'nivel' => '1'],
            ['nombre' => 'DIRECTOR (a) NACIONAL DE EVENTO', 'nivel' => '1'],
            ['nombre' => 'EQUIPO NACIONAL DE EVENTO', 'nivel' => '1'],
            ['nombre' => 'JEFE (a) DE ESTADO', 'nivel' => '2'],
            ['nombre' => 'ORGANIZADOR (a) DE ESTADO', 'nivel' => '2'],
            ['nombre' => 'FUNCIONAMIENTO ESTADAL DE ORGANIZACION', 'nivel' => '2'],
            ['nombre' => 'EQUIPO ESTADAL DE ORGANIZACION', 'nivel' => '2'],
            ['nombre' => 'PUESTO DE COMANDO ESTADAL', 'nivel' => '2'],
            ['nombre' => 'EQUIPO ESTADAL DE PUESTO DE COMANDO', 'nivel' => '2'],
            ['nombre' => 'FORMADOR (a) ESTADAL', 'nivel' => '2'],
            ['nombre' => 'FUNCIONAMIENTO ESTADAL DE FORMACION', 'nivel' => '2'],
            ['nombre' => 'EQUIPO ESTADAL DE FORMACION', 'nivel' => '2'],
            ['nombre' => 'MOVILIZACION Y PROPAGANDA ESTADAL', 'nivel' => '2'],
            ['nombre' => 'FUNCIONAMIENTO ESTADAL DE MOVILIZACION Y PROPAGANDA', 'nivel' => '2'],
            ['nombre' => 'EQUIPO ESTADAL DE MOVILIZACION Y PROPAGANDA', 'nivel' => '2'],
            ['nombre' => 'MICROMISION FRANCISCO DE MIRANDA ESTADAL', 'nivel' => '2'],
            ['nombre' => 'FUNCIONAMIENTO ESTADAL DE MICROMISION FRANCISCO DE MIRANDA', 'nivel' => '2'],
            ['nombre' => 'EQUIPO ESTADAL DE LA MICROMISION FRANCISCO DE MIRANDA', 'nivel' => '2'],
            ['nombre' => 'SOMOS VENEZUELA ESTADAL', 'nivel' => '2'],
            ['nombre' => 'FUNCIONAMIENTO ESTADAL DE SOMOS VENEZUELA', 'nivel' => '2'],
            ['nombre' => 'EQUIPO ESTADAL DE SOMOS VENEZUELA', 'nivel' => '2'],
            ['nombre' => 'DEFENZA INTEGRAL DE LA PATRIA ESTADAL', 'nivel' => '2'],
            ['nombre' => 'FUNCIONAMIENTO ESTADAL DE DEFENZA INTEGRAL DE LA PATRIA', 'nivel' => '2'],
            ['nombre' => 'EQUIPO ESTADAL DE DEFENZA INTEGRAL DE LA PATRIA ESTADAL', 'nivel' => '2'],
            ['nombre' => 'GMVV ESTADAL', 'nivel' => '2'],
            ['nombre' => 'EQUIPO ESTADAL DE LA GMVV', 'nivel' => '2'],
            ['nombre' => 'EME EN INSTITUCION', 'nivel' => '2'],
            ['nombre' => 'EQUIPO ESTADAL EN INSTITUCION', 'nivel' => '2'],
            ['nombre' => 'GOBERNADOR (a)', 'nivel' => '2'],
            ['nombre' => 'ALCALDE (sa)', 'nivel' => '3'],
            ['nombre' => 'CONSTITUYENTE', 'nivel' => '3'],
            ['nombre' => 'LEGISLADOR (a)', 'nivel' => '3'],
            ['nombre' => 'CONSEJAL', 'nivel' => '3'],
            ['nombre' => 'DIRECTOR MUNICIPAL', 'nivel' => '3'],
            ['nombre' => 'ORGANIZADOR (a) MUNICIPAL', 'nivel' => '3'],
            ['nombre' => 'PUESTO DE COMANDO MUNICIPAL', 'nivel' => '3'],
            ['nombre' => 'FORMADOR (a) MUNICIPAL', 'nivel' => '3'],
            ['nombre' => 'PROPAGANDA MUNICIPAL', 'nivel' => '3'],
            ['nombre' => 'DEFENZA INTEGRAL DE LA PATRIA MUNICIPAL', 'nivel' => '3'],
            ['nombre' => 'ECONOMO (a) MUNICIPAL', 'nivel' => '3'],
            ['nombre' => 'MICROMISION FRANCISCO DE MIRANDA MUNICIPAL', 'nivel' => '3'],
            ['nombre' => 'SOMOS VENEZUELA MUNICIPAL', 'nivel' => '3'],
            ['nombre' => 'JEFE (a) DE PARROQUIA', 'nivel' => '4'],
            ['nombre' => 'ORGANIZADOR (a) PARROQUIAL', 'nivel' => '4'],
            ['nombre' => 'PUESTO DE COMANDO MUNICIPAL', 'nivel' => '4'],
            ['nombre' => 'FORMADOR (a) PARROQUIAL', 'nivel' => '4'],
            ['nombre' => 'PROPAGANDA PARROQUIAL', 'nivel' => '4'],
            ['nombre' => 'DEFENZA INTEGRAL DE LA PATRIA PARROQUIAL', 'nivel' => '4'],
            ['nombre' => 'ECONOMO (a) PARROQUIAL', 'nivel' => '4'],
            ['nombre' => 'MICROMISION FRANCISCO DE MIRANDA PARROQUIAL', 'nivel' => '4'],
            ['nombre' => 'SOMOS VENEZUELA PARROQUIAL', 'nivel' => '4'],
            ['nombre' => 'JEFE (a) DE NBC', 'nivel' => '5'],
            ['nombre' => 'ORGANIZADOR (a) DE NBC', 'nivel' => '5'],
            ['nombre' => 'FORMADOR (a) DE NBC', 'nivel' => '5'],
            ['nombre' => 'MOVILIZADOR (a) DE NBC', 'nivel' => '5'],
            ['nombre' => 'SOMOS VENEZUELA', 'nivel' => '5'],
            ['nombre' => 'CLAP', 'nivel' => '5'],
            ['nombre' => 'EULALIA BUROZ', 'nivel' => '5'],
            ['nombre' => 'CARNET DE LA PATRIA', 'nivel' => '5'],
            ['nombre' => 'CASAS DE ALIMENTACION', 'nivel' => '5'],
            ['nombre' => 'ECO-PATRIA', 'nivel' => '5'],
            ['nombre' => 'MICRO MISION PRODUCTIVA FRANSISCO DE MIRANDA', 'nivel' => '5'],
            ['nombre' => 'GMVV-URBANISMOS', 'nivel' => '5'],
            ['nombre' => 'BASES DE MISIONES', 'nivel' => '5']            
        ]);
    }
}
